#!/bin/bash

if [ $1 = "s" ]; then
	shutdown -P 0

elif [ $1 = "r" ]; then
	reboot

elif [ $1 = "l" ]; then
	i3lock

elif [ $1 = "ss" ]; then
	systemctl suspend && i3lock

else
	echo "Invalid option"
fi
